Dev/251 refactor logging
HBPMedical/portal-backend pull request #16
Opened 2020-10-13 16:09 UTC by KFilippopolitis

Reworked the whole logging in the solution.
Disabled the spring-boot logs.

2020-10-13 16:39 UTC, ThanKarab requested changes

2020-10-13 16:39 UTC, ThanKarab commented on src/main/java/eu/hbp/mip/controllers/ExperimentApi.java
> +        String algorithmType = experimentExecutionDTO.getAlgorithms().get(0).getType();
algorithm type does not need to be logged.

2020-10-13 16:39 UTC, ThanKarab commented on src/main/java/eu/hbp/mip/controllers/ExperimentApi.java
> +        Logging.LogUserAction(user.getUsername(), "(POST) /experiments/runAlgorithm", "Executing " + algorithmName + " with algorithmType : " + algorithmType + ".");
The parameters should be logged.

2020-10-14 10:28 UTC, KFilippopolitis commented on src/main/java/eu/hbp/mip/controllers/ExperimentApi.java
> +        Logging.LogUserAction(user.getUsername(), "(POST) /experiments/runAlgorithm", "Executing " + algorithmName + " with algorithmType : " + algorithmType + ".");
The whole experimentExecutionDTO?

2020-10-15 06:49 UTC, ThanKarab approved these changes

2020-10-15 07:06 UTC, merged