Dev/mip 62/mip engine integration with the mip portalbackend
HBPMedical/portal-backend pull request #23
Opened 2021-07-05 14:40 UTC by KFilippopolitis

2021-07-08 11:21 UTC, ThanKarab requested changes
Nice work!

Quick summary:
1) Remove all converters and create constructors.
2) Move Galaxy calls to a separate "GalaxyService".
3) Rename all internal classes with the proper prefix (MIPEngine or Exareme)

minor: use localhost instead of internal ip.

2021-07-08 11:21 UTC, ThanKarab commented on src/main/java/eu/hbp/mip/models/DTOs/MIPEngineAlgorithmDTO.java
> +    public static class ParameterDTO {
nit: Rename to MIPEngineAlgorithmParameterDTO?

2021-07-08 11:21 UTC, ThanKarab commented on src/main/java/eu/hbp/mip/models/DTOs/MIPEngineAlgorithmDTO.java
> +        public ExaremeAlgorithmRequestParamDTO convertToexaremeAlgorithmRequestDTO(String name){
After a discussion we had, we decided to remove all "converters" and change them to constructors.

2021-07-08 11:21 UTC, ThanKarab commented on src/main/java/eu/hbp/mip/models/DTOs/MIPEngineAlgorithmDTO.java
> +    public static class InputdataDTO {
nit: MIPEngineInputDataDTO?

2021-07-08 11:21 UTC, ThanKarab commented on src/main/java/eu/hbp/mip/models/DTOs/MIPEngineAlgorithmDTO.java
> +    public static class InputDataDetailDTO {
nit: prefix with MIPEngine?

2021-07-08 11:21 UTC, ThanKarab commented on src/main/java/eu/hbp/mip/models/DTOs/MIPEngineTabularVisualizationDTO.java
> +public class MIPEngineTabularVisualizationDTO {
This does not belong to MIPEngine but to portal-backend / frontend. I think no prefix is needed for that... Not sure though.

2021-07-08 11:21 UTC, ThanKarab commented on src/main/resources/application.yml
> +    algorithmsUrl: "http://192.168.124.129:5000/algorithms"
nit: localhost?

2021-07-09 11:53 UTC, KFilippopolitis commented on docker/README.md
> +* MIPENGINE_URL: URL to MIPENGINE server. Default is "http://192.168.124.129:5000" .
We need mip engine to be dockerized to access the localhost.

2021-07-19 08:38 UTC, ThanKarab approved these changes

2021-07-19 08:38 UTC, merged